"""Created image column for observations

Revision ID: 3f1c6a9dc494
Revises: 0d269ad93bdf
Create Date: 2023-05-03 11:16:19.007364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1c6a9dc494'
down_revision = '0d269ad93bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
