"""bigfixed promary key issue

Revision ID: dd1a591c60da
Revises: 36402885799e
Create Date: 2023-04-25 09:04:57.700236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1a591c60da'
down_revision = '36402885799e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observations_plant_id_plants'), 'plants', ['plant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_observations_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_observations_plant_id_plants'), type_='foreignkey')
        batch_op.drop_column('plant_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
